site_name: TFM Records Wiki
site_url: https://wiki.tfmrecords.com

repo_url: https://github.com/TFMRecords/wiki
repo_name: GitHub
edit_uri: edit/main/docs/

nav:
  - index.md
  - rules.md
  - recording.md
  - using-module.md
  - join-discord.md

  - module:
    - commands.md
    - hotkeys.md

  - game:
    - official-standalones.md
    - perm-codes.md

  - community:
    - website.md
    - discord.md
    - youtube.md


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    # Dark mode
    - scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light mode
    - scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          nav_translations:
            community: Community
            module: Module
            game: Game

        - locale: tr
          name: Türkçe
          nav_translations:
            community: Topluluk
            module: Modül
            game: Oyun

        - locale: es
          name: Español
          nav_translations:
            community: Comunidad
            module: Módulo
            game: Juego

        - locale: pt
          name: Português
          nav_translations:
            community: Comunidade
            module: Módulo
            game: Jogo

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
